### PR TITLE
Fix for malformated mobile signing button

### PR DESCRIPTION
**Pull request by grethler**
image
image

### CODE REVIEW

**Review by muhammad-fiaz — APPROVED** [review]
Looks good! Thank you, @grethler, for your contribution and for fixing the malformed mobile signing button issue in #687! Your work is greatly appreciated, and the fix improves the UI of the button in mobile view. I'll go ahead and approve the changes. Thanks again for taking the time to help! :)

**Comment by muhammad-fiaz** [comment]
> the "Sign In" still isn't centered and I couldn't fix that

image
🤔?

**Comment by grethler** [comment]
> > the "Sign In" still isn't centered and I couldn't fix that
> 
> 
> 
> image
> 
>  its works by displaying center 🤔?


I could not center the <a ...>Sign In</a> inside of the button. Ir you look closely the text itself seems to be more to the left than to the right.

**Comment by muhammad-fiaz** [comment]
> > > the "Sign In" still isn't centered and I couldn't fix that
> > 
> > 
> > image
> > its works by displaying center 🤔?
> 
> I could not center the `<a ...>Sign In</a>` inside of the button. Ir you look closely the text itself seems to be more to the left than to the right.

that may be due to the css/scss styles that have been assigned the component which overrides the tailwindcss

**Pull request closed without merging**
